name: dart_server
description: A Dart server to use with your Flutter project
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ^1.17.0
  crypt: ^4.3.1
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_secure_cookie: ^1.3.0
  shelf_static: ^1.1.3
  sqlite3: ^1.9.2
  sqlite3_flutter_libs: ^0.5.41
  uuid: ^3.0.7
